// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2bKmBcSG_SqUbE6eoAD5wozkSaz_PygA',
    appId: '1:186645994478:web:8fb998cc9576956e47ccff',
    messagingSenderId: '186645994478',
    projectId: 'mindmover-13852',
    authDomain: 'mindmover-13852.firebaseapp.com',
    storageBucket: 'mindmover-13852.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRxgqOyQY0iT83RDo-yDZBvtxiBVQpCZ8',
    appId: '1:186645994478:android:f00fd09bf3f2096147ccff',
    messagingSenderId: '186645994478',
    projectId: 'mindmover-13852',
    storageBucket: 'mindmover-13852.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOk4M23naZHwJBklgRXIMIRq45cTTczr4',
    appId: '1:186645994478:ios:69c8c5b71b4bbb7a47ccff',
    messagingSenderId: '186645994478',
    projectId: 'mindmover-13852',
    storageBucket: 'mindmover-13852.appspot.com',
    iosBundleId: 'com.example.eegApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOk4M23naZHwJBklgRXIMIRq45cTTczr4',
    appId: '1:186645994478:ios:126a29e13a136c2047ccff',
    messagingSenderId: '186645994478',
    projectId: 'mindmover-13852',
    storageBucket: 'mindmover-13852.appspot.com',
    iosBundleId: 'com.example.eegApplication.RunnerTests',
  );
}
